- name: Configure prometheus
  hosts: all
  strategy: free
  become: yes
  tasks:
    - name: Create configuration directory
      file:
        path: "{{ prometheus_configuration_dir }}"
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Copy configuration files
      template:
        src: "prometheus.yml.j2"
        dest: "{{ prometheus_configuration_dir }}/prometheus.yml"
        owner: root
        group: root
        mode: "0644"
